#!/bin/sh

dir="$HOME"/.sfeed
lsfeed() {
	sfeed_plain_trimmed "$dir/feeds/$feed"
}

# Update feeds if haven't already in the past 12 hours
# ! with -lt handles garbage data in file while only -gt does not
if ! [ "$(expr $(date +%s) - $(cat $dir/lastautoupdate 2>/dev/null))" \
	-lt 43200 ]; then
	sfeed_update
	date "+%s" > $dir/lastautoupdate
fi

while true; do
	feed="$(grep 'feed "[^"]*" "[^"]*"' $dir/sfeedrc | cut -d \" -f 2 | \
		dmenu -i -l $DMENULINENUM)"
	[ -z "$feed" ] && break
	while true; do
		selection="$(lsfeed | awk -F '\t' '{print $1}'| \
			dmenu -i -l $DMENULINENUM)"
		[ -z "$selection" ] && break
		eval "$BROWSER $(lsfeed | grep "$selection" | \
			awk -F '\t' '{print $2}')" & exit 0
	done
done
