#!/bin/sh

set -x

while true; do
	action="$(printf "%s\n" \
		"Browser" \
		"RSS" \
		"Sound" \
		"Networking" \
		"Virtual Machines" \
		"Passwords" \
		"Display" \
		"System" | \
       		dmenu -i -l "$DMENULINENUM")"
	
	[ -z "$action" ] && exit 1
	
	case "$action" in
		"Browser") exec $BROWSER;;
		"RSS") dmenu_rss && exit "$?";;
		"Terminal") exec tabbed -g 1200x750 -r 2 st -w '';;
		"Sound") exec st -w '' alsamixer;;
		"Networking") exec st -w '' nmtui;;
		"Virtual Machines") exec st -e doas vm.sh \
			"$(for vmdir in /var/vm/*; do
			[ -d "$vmdir" ] && basename "$vmdir"
		done | dmenu -i -l "$DMENULINENUM")" delay;;
		"Passwords") dmenu_passwd && exit "$?";;
		"Display") dmenu_display && exit "$?";;
		"System") dmenu_system && exit "$?";;
	esac
done
