#!/bin/sh

dir="$HOME"/.passwords
field=5

copy() {
	xclip -selection clipboard
}

grep -v '^#' "$dir/$(find "$dir" -type f | cut -d / -f "$field"- | sort | \
	dmenu -i -l "$DMENULINENUM")" | copy

# Clear clipboard after 30 seconds
sleep 30
printf "" | copy
