#!/bin/sh

min=15
increment=5

display="$(xrandr | awk '/ connected/ { print $1 }')"

x=100
level="$(while [ "$x" -ge "$min" ]; do
	printf '%s\n' "$x"
	x=$((x - increment))
done | dmenu -i -l "$DMENULINENUM")"
brightness="$(awk "BEGIN { print $level/100 }")"

xrandr --output "$display" --brightness "$brightness"

exit "$?"
