#!/bin/sh

dir="$HOME"/.passwords
field=5

copy() {
	xclip -selection clipboard
}

cat "$dir/$(find "$dir" -type f | cut -d / -f "$field"- | sort | \
	dmenu -i -l "$DMENULINENUM")" | grep -v '^#' | copy

# Clear clipboard after 30 seconds
sleep 30
printf "" | copy
