#!/bin/sh

dir=~/.passwords
field=5

cat "$dir/$(find $dir -type f | cut -d / -f $field- | sort | \
	dmenu -i -l $DMENULINENUM)" | grep -v '^#' | xclip -selection CLIPBOARD

# Clear clipboard after 30 seconds
sleep 30
printf "" | xclip -selection CLIPBOARD
