#!/bin/sh

_slock=0

while true; do
	action="$(printf '%s\n' \
		'Suspend' \
		'Hibernate' \
		'Logout' \
		'Reboot' \
		'Shutdown' | \
		dmenu -i -l "$DMENULINENUM")"

	[ -z "$action" ] && exit 1
	
	case "$action" in
		Suspend)
			[ "$_slock" -eq 1 ] && slock &
			exec systemctl suspend
		;;
		Hibernate)
			[ "$_slock" -eq 1 ] && slock &
			exec systemctl hibernate
		;;
		Logout)
			exec pkill -u "$(whoami)"
		;;
		Reboot)
			exec shutdown -r now
		;;
		Shutdown)
			exec shutdown -P now
		;;
	esac 
done
