#!/bin/sh
# /etc/X11/xinit/xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for file in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$file" ] && . "$file"
 done
 unset file
fi

# Enable translucency
picom --blur-method box &

# Enable status bar
statusbar.sh &

# Start off in floating layout
#(sleep .3; xdotool key super+f) &

# Changes font size of programs such as packettracer and wireshark
QT_DEVICE_PIXEL_RATIO=2
export QT_DEVICE_PIXEL_RATIO

# Librewolf/Firefox font/scale settings can be changed with 
# about:config -> layout.css.devPixelsPerPx
BROWSER=librewolf
export BROWSER

# How many lines will dmenu(1) (sometimes) display by in scripts
# dmenu has been built to hide any extra lines that are empty
DMENULINENUM=25
export DMENULINENUM

# Permit any user to run X applications (needed for vm.sh)
# Potentially a security risk, but network is disallowed access to X anyways
xhost +local:

# Start the suckless.org Dynamic Window Manager
exec dwm
